name: .NET CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify .NET
        run: dotnet --version

      - name: Restore
        run: dotnet restore Calculator.sln

      - name: Build
        run: dotnet build Calculator.sln --configuration Release --no-restore

      - name: Lint
        run: dotnet format Calculator.sln --verify-no-changes
        continue-on-error: true

      - name: Test
        run: dotnet test Calculator.sln

      - name: Publish
        run: dotnet publish Calculator/Calculator.csproj -c Release -o publish

      - name: Run Application
        run: dotnet publish/Calculator.dll
